apiVersion: v1
kind: Service
metadata:
  labels:
    app: apiserver
    component: hodor-api
  name: hodor-api-service
spec:
  ports:
  - port: 80
    targetPort: 3636
    name: "http"
    protocol: TCP
  selector:
    app: apiserver
    component: hodor-api
  type: LoadBalancer 