apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels: 
    app: taskQueue
    component: rabbitmq
  name: rabbitmq-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: taskQueue
        component: rabbitmq
    spec:
      containers:
      - name: rabbitmq
        image: rabbitmq
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5672